### ISSUE TITLE
USA- Web experience

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-drive#94]
Not sure if this is coding or bandwidth, but using Firefox or Chrome is painfully slow, particularly in the directory where you have backed up your mobile photos.  (Using latest Windows 10 updated versions of both browsers)

**Comment by DanielProg39** [comment]
The servers are in Germany, so this is the fault of them being geographically far from you. It's been announced that Filen staff are thinking about opening servers in the USA, because this will make the experience much faster for Americans, but there's also a privacy issue exposed by these servers being under American legislation, especially data legislation. So low speeds are basically the cost of increased privacy in your case.

**Comment by telrod11** [comment]
Makes sense.  

 I do have data stored with Mega, and don't experience this slowdown, is this an encryption issue, because I do believe their servers are not USA based either. 

Just a thought

**Comment by DanielProg39** [comment]
I don't think that this is an encryption issue, because I don't have any speed issues and I am in Ukraine, which is a lot closer to Germany than the USA. Mega is faster in the US as it has servers in Canada

**Comment by telrod11** [comment]
OK, thanks for that.
